// comparison-test/benchmark/apps/round-2/pomodoro-svelte/src/lib/Controls.svelte
<script>
  let { isRunning, start, pause, reset, activeColor } = $props();
</script>

<div class="controls">
  {#if isRunning}
    <button
      class="control-btn primary"
      onclick={pause}
      style="background: {activeColor};"
      aria-label="Pause timer"
    >
      <svg width="20" height="20" viewBox="0 0 20 20" fill="currentColor">
        <rect x="4" y="3" width="4" height="14" rx="1" />
        <rect x="12" y="3" width="4" height="14" rx="1" />
      </svg>
      Pause
    </button>
  {:else}
    <button
      class="control-btn primary"
      onclick={start}
      style="background: {activeColor};"
      aria-label="Start timer"
    >
      <svg width="20" height="20" viewBox="0 0 20 20" fill="currentColor">
        <path d="M6 3.5L16 10L6 16.5V3.5Z" />
      </svg>
      Start
    </button>
  {/if}

  <button
    class="control-btn secondary"
    onclick={reset}
    aria-label="Reset timer"
  >
    <svg width="18" height="18" viewBox="0 0 18 18" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round">
      <path d="M1 1v5h5" />
      <path d="M3.51 11a6.5 6.5 0 1 0 1.13-6.5L1 6" />
    </svg>
    Reset
  </button>
</div>

<style>
  .controls {
    display: flex;
    gap: 0.75rem;
    justify-content: center;
  }

  .control-btn {
    display: inline-flex;
    align-items: center;
    gap: 0.5rem;
    padding: 0.75rem 1.5rem;
    border-radius: 14px;
    font-size: 0.9375rem;
    font-weight: 600;
    letter-spacing: -0.01em;
  }

  .primary {
    color: white;
    box-shadow: var(--shadow);
  }

  .primary:hover {
    opacity: 0.9;
    transform: translateY(-1px);
    box-shadow: var(--shadow-lg);
  }

  .primary:active {
    transform: translateY(0);
  }

  .secondary {
    background: var(--btn-bg);
    color: var(--btn-text);
  }

  .secondary:hover {
    background: var(--btn-hover);
    transform: translateY(-1px);
  }

  .secondary:active {
    transform: translateY(0);
  }
</style>

// comparison-test/benchmark/apps/round-2/pomodoro-react/src/components/Controls.jsx
import './Controls.css'

export default function Controls({ isRunning, onStart, onPause, onReset }) {
  return (
    <div className="controls">
      {isRunning ? (
        <button
          className="controls__btn controls__btn--pause"
          onClick={onPause}
          aria-label="Pause timer"
        >
          <svg width="20" height="20" viewBox="0 0 20 20" fill="currentColor">
            <rect x="4" y="3" width="4" height="14" rx="1" />
            <rect x="12" y="3" width="4" height="14" rx="1" />
          </svg>
          Pause
        </button>
      ) : (
        <button
          className="controls__btn controls__btn--start"
          onClick={onStart}
          aria-label="Start timer"
        >
          <svg width="20" height="20" viewBox="0 0 20 20" fill="currentColor">
            <path d="M6 3.5a1 1 0 0 1 1.5-.86l9 5.2a1 1 0 0 1 0 1.72l-9 5.2A1 1 0 0 1 6 13.9V3.5z" />
          </svg>
          Start
        </button>
      )}
      <button
        className="controls__btn controls__btn--reset"
        onClick={onReset}
        aria-label="Reset timer"
      >
        <svg width="18" height="18" viewBox="0 0 18 18" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round">
          <path d="M3.5 3.5v4h4" />
          <path d="M3.5 7.5A6 6 0 1 1 3 10.5" />
        </svg>
        Reset
      </button>
    </div>
  )
}
